echo Copie du fichier .war vers le répertoire webapps de Tomcat...
copy target\biblio-spring-1.0.war "D:\SOARY\Downloads\tomcat-10.1.28-windows-x64\apache-tomcat-10.1.28\webapps"

echo Lancement de Tomcat...
call "D:\SOARY\Downloads\tomcat-10.1.28-windows-x64\apache-tomcat-10.1.28\bin\startup.bat"