-- Création des tables

CREATE TABLE abonnement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_debut_abonnement DATE,
    fin_abonnement DATE,
    nb_mois_abonnement INTEGER NOT NULL,
    nom_personne VARCHAR(255)
);

CREATE TABLE formul_emprunt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_formule VARCHAR(255),
    nombre_de_mois INTEGER NOT NULL
);

CREATE TABLE livre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_exemplaire VARCHAR(255),
    auteur VARCHAR(255),
    image VARCHAR(255),
    titre VARCHAR(255)
);

CREATE TABLE sign_in (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    mot_de_passe VARCHAR(255),
    numero INTEGER NOT NULL,
    profil VARCHAR(255),
    user_name VARCHAR(255)
);

CREATE TABLE emprunt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_debut_emprunt TIMESTAMP,
    date_fin_emprunt TIMESTAMP,
    id_livre BIGINT,
    id_nom_emprunteur BIGINT,
    type_de_lecture VARCHAR(255)
);

CREATE TABLE reservation (
    id_reservation BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sign_in INTEGER NOT NULL,
    id_livre BIGINT NOT NULL,
    date_reservation DATE NOT NULL,
    statut VARCHAR(255) DEFAULT 'en attente'
);

-- Clés étrangères

ALTER TABLE reservation
ADD CONSTRAINT fk_livre FOREIGN KEY (id_livre) REFERENCES livre(id);

ALTER TABLE reservation
ADD CONSTRAINT fk_signin FOREIGN KEY (id_sign_in) REFERENCES sign_in(id);

ALTER TABLE livre ADD COLUMN age_minimum INT;
ALTER TABLE sign_in ADD COLUMN date_naissance DATE;
ALTER TABLE sign_in ADD COLUMN quota_maison INT DEFAULT 3;

CREATE TABLE rendre_livre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_emprunt BIGINT NOT NULL,
    date_retour TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    commentaire VARCHAR(255),

    CONSTRAINT fk_emprunt FOREIGN KEY (id_emprunt) REFERENCES emprunt(id)
);
